spring.application.name=mvc

spring.h2.console.enabled=true


#by default h2 uses in memory db that erase when shut down

#way of creating file db
spring.datasource.url=jdbc:h2:file:D:/SpringBoot/mvc/db
spring.datasource.username=rohandb
spring.datasource.password=pass

spring.jpa.hibernate.ddl-aut0=create